defmodule DAOSystemBasedOnGithubWeb.GithubLinkerLive do
    use DAOSystemBasedOnGithubWeb, :live_view
    @impl true
    def mount(_params, _session, socket) do
      {:ok, socket}
    end
  
    @impl true
    def handle_event(_key, _params, socket) do
      {:noreply, socket}
    end
  
    def handle_params(_params, _url, socket) do
      {:noreply, socket}
    end
  
    @impl true
    def render(assigns) do
      ~H"""
      <.container class="mt-10 mb-32">
        <center><.h1 label="Github Linker(Developing)" />        </center>
        <.h5>
            Github Linker is an application that based on 
                MoveDID and various flow payment protocols, like 
                Moveflow, to establish a topological network by interlinking related repositories.<br><br>
                This network enables economic income generated by one repository to be automatically distributed to other relevant repositories and contributors through a chain distribution agreement.
                <br><br>
                So that <b>the Public Goods</b> can get its due benefits, such as SDK type projects.
                <br><br>
                💡 The Map below is generated automatically according to the relationships of the repositories.  The label on the Repo connection line refers to the proportion of the amount allocated.
        </.h5>
        <br><hr><br>
        <.form_label field="Input a repo name to see it's relationships:" />
        <.text_input placeholder="MoveDID" />
        <br>
        <.form_label field="Or input a organzation name to see the repos' network under this org:" />
        <.text_input placeholder="NonceGeek" />
        <br><br>
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1121pt" height="324pt" viewBox="0.00 0.00 1121.00 324.00">
            <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 320)">
            <title>NonceGeekRepoTree</title>
            <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-320 1117,-320 1117,4 -4,4"/>
            <g id="clust1" class="cluster">
            <title>cluster_1</title>
            <polygon fill="none" stroke="#0000ff" points="9,-119.6 9,-196.4 553,-196.4 553,-119.6 9,-119.6"/>
            <text text-anchor="middle" x="281" y="-179.8" font-family="Times,serif" font-size="14.00" fill="#000000">MoveDID</text>
            </g>
            <g id="clust2" class="cluster">
            <title>cluster_2</title>
            <polygon fill="none" stroke="#0000ff" points="9,-8 9,-84.8 553,-84.8 553,-8 9,-8"/>
            <text text-anchor="middle" x="281" y="-68.2" font-family="Times,serif" font-size="14.00" fill="#000000">TaiShang Micro FaaS System</text>
            </g>
            <g id="clust3" class="cluster">
            <title>cluster_3</title>
            <polygon fill="none" stroke="#0000ff" points="561,-8 561,-84.8 1105,-84.8 1105,-8 561,-8"/>
            <text text-anchor="middle" x="833" y="-68.2" font-family="Times,serif" font-size="14.00" fill="#000000">Web3 Aptos Ex</text>
            </g>
            <g id="clust4" class="cluster">
            <title>cluster_4</title>
            <polygon fill="none" stroke="#0000ff" points="8,-231.2 8,-308 553,-308 553,-231.2 8,-231.2"/>
            <text text-anchor="middle" x="280.5" y="-291.4" font-family="Times,serif" font-size="14.00" fill="#000000">Move Airdropper based on Github</text>
            </g>
            <!-- cluster_1_repo -->
            <g id="node1" class="node">
            <title>cluster_1_repo</title>
            <g id="a_node1"><a xlink:href="https://github.com/NonceGeek/MoveDID" xlink:title="Repo" target="_blank">
            <polygon fill="none" stroke="#000000" points="545,-163.6 491,-163.6 491,-127.6 545,-127.6 545,-163.6"/>
            <text text-anchor="middle" x="518" y="-141.4" font-family="Times,serif" font-size="14.00" fill="#000000">Repo</text>
            </a>
            </g>
            </g>
            <!-- cluster_2_repo -->
            <g id="node6" class="node">
            <title>cluster_2_repo</title>
            <g id="a_node6"><a xlink:href="https://github.com/NonceGeek/tai_shang_micro_faas_system" xlink:title="Repo" target="_blank">
            <polygon fill="none" stroke="#000000" points="545,-52 491,-52 491,-16 545,-16 545,-52"/>
            <text text-anchor="middle" x="518" y="-29.8" font-family="Times,serif" font-size="14.00" fill="#000000">Repo</text>
            </a>
            </g>
            </g>
            <!-- cluster_1_repo&#45;&gt;cluster_2_repo -->
            <g id="edge2" class="edge">
            <title>cluster_1_repo-&gt;cluster_2_repo</title>
            <path fill="none" stroke="#000000" d="M518,-127.1715C518,-109.539 518,-82.6924 518,-62.3391"/>
            <polygon fill="#000000" stroke="#000000" points="521.5001,-62.0855 518,-52.0856 514.5001,-62.0856 521.5001,-62.0855"/>
            <text text-anchor="middle" x="532.5803" y="-97" font-family="Times,serif" font-size="14.00" fill="#000000">2.5%</text>
            </g>
            <!-- cluster_3_repo -->
            <g id="node11" class="node">
            <title>cluster_3_repo</title>
            <g id="a_node11"><a xlink:href="https://github.com/NonceGeek/web3_aptos_ex" xlink:title="Repo" target="_blank">
            <polygon fill="none" stroke="#000000" points="1097,-52 1043,-52 1043,-16 1097,-16 1097,-52"/>
            <text text-anchor="middle" x="1070" y="-29.8" font-family="Times,serif" font-size="14.00" fill="#000000">Repo</text>
            </a>
            </g>
            </g>
            <!-- cluster_1_repo&#45;&gt;cluster_3_repo -->
            <g id="edge3" class="edge">
            <title>cluster_1_repo-&gt;cluster_3_repo</title>
            <path fill="none" stroke="#000000" d="M545.0663,-145.2646C639.0396,-143.6682 950.0383,-134.6492 1034,-84.8 1043.4806,-79.1712 1051.1215,-69.9632 1056.8835,-60.9218"/>
            <polygon fill="#000000" stroke="#000000" points="1060.0256,-62.4805 1062.0179,-52.0747 1053.9713,-58.9669 1060.0256,-62.4805"/>
            <text text-anchor="middle" x="1021.3303" y="-97" font-family="Times,serif" font-size="14.00" fill="#000000">5%</text>
            </g>
            <!-- cluster_1_contributors -->
            <g id="node2" class="node">
            <title>cluster_1_contributors</title>
            <g id="a_node2"><a xlink:href="https://github.com/NonceGeek/MoveDID#contributors" xlink:title="Contributors" target="_blank">
            <polygon fill="none" stroke="#000000" points="473.2745,-163.6 386.7255,-163.6 386.7255,-127.6 473.2745,-127.6 473.2745,-163.6"/>
            <text text-anchor="middle" x="430" y="-141.4" font-family="Times,serif" font-size="14.00" fill="#000000">Contributors</text>
            </a>
            </g>
            </g>
            <!-- cluster_1_money_history -->
            <g id="node3" class="node">
            <title>cluster_1_money_history</title>
            <g id="a_node3"><a xlink:href="https://github.com/NonceGeek/MoveDID#money-history" xlink:title="Money History" target="_blank">
            <polygon fill="none" stroke="#000000" points="368.6523,-163.6 267.3477,-163.6 267.3477,-127.6 368.6523,-127.6 368.6523,-163.6"/>
            <text text-anchor="middle" x="318" y="-141.4" font-family="Times,serif" font-size="14.00" fill="#000000">Money History</text>
            </a>
            </g>
            </g>
            <!-- cluster_1_distributed_rules -->
            <g id="node4" class="node">
            <title>cluster_1_distributed_rules</title>
            <g id="a_node4"><a xlink:href="https://github.com/NonceGeek/MoveDID#distributed-rules" xlink:title="Distributed Rules" target="_blank">
            <polygon fill="none" stroke="#000000" points="249.3758,-163.6 134.6242,-163.6 134.6242,-127.6 249.3758,-127.6 249.3758,-163.6"/>
            <text text-anchor="middle" x="192" y="-141.4" font-family="Times,serif" font-size="14.00" fill="#000000">Distributed Rules</text>
            </a>
            </g>
            </g>
            <!-- cluster_1_movedid -->
            <g id="node5" class="node">
            <title>cluster_1_movedid</title>
            <g id="a_node5"><a xlink:href="https://explorer.aptoslabs.com/account/0x2df41622c0c1baabaa73b2c24360d205e23e803959ebbcb0e5b80462165893ed?network=mainnet" xlink:title="DID: 0x2d...ed" target="_blank">
            <polygon fill="none" stroke="#000000" points="116.979,-163.6 17.021,-163.6 17.021,-127.6 116.979,-127.6 116.979,-163.6"/>
            <text text-anchor="middle" x="67" y="-141.4" font-family="Times,serif" font-size="14.00" fill="#000000">DID: 0x2d...ed</text>
            </a>
            </g>
            </g>
            <!-- cluster_2_movedid -->
            <g id="node7" class="node">
            <title>cluster_2_movedid</title>
            <g id="a_node7"><a xlink:href="https://explorer.aptoslabs.com/account/0x06a19c3df50ea7e7b8e686246db5c4d98affa4aa0de05285688a90342751eeed" xlink:title="DID: 0x06...ed" target="_blank">
            <polygon fill="none" stroke="#000000" points="472.979,-52 373.021,-52 373.021,-16 472.979,-16 472.979,-52"/>
            <text text-anchor="middle" x="423" y="-29.8" font-family="Times,serif" font-size="14.00" fill="#000000">DID: 0x06...ed</text>
            </a>
            </g>
            </g>
            <!-- cluster_2_contributors -->
            <g id="node8" class="node">
            <title>cluster_2_contributors</title>
            <g id="a_node8"><a xlink:href="https://github.com/NonceGeek/tai_shang_micro_faas_system#contributors" xlink:title="Contributors" target="_blank">
            <polygon fill="none" stroke="#000000" points="355.2745,-52 268.7255,-52 268.7255,-16 355.2745,-16 355.2745,-52"/>
            <text text-anchor="middle" x="312" y="-29.8" font-family="Times,serif" font-size="14.00" fill="#000000">Contributors</text>
            </a>
            </g>
            </g>
            <!-- cluster_2_money_history -->
            <g id="node9" class="node">
            <title>cluster_2_money_history</title>
            <g id="a_node9"><a xlink:href="https://github.com/NonceGeek/tai_shang_micro_faas_system#money-history" xlink:title="Money History" target="_blank">
            <polygon fill="none" stroke="#000000" points="250.6523,-52 149.3477,-52 149.3477,-16 250.6523,-16 250.6523,-52"/>
            <text text-anchor="middle" x="200" y="-29.8" font-family="Times,serif" font-size="14.00" fill="#000000">Money History</text>
            </a>
            </g>
            </g>
            <!-- cluster_2_distributed_rules -->
            <g id="node10" class="node">
            <title>cluster_2_distributed_rules</title>
            <g id="a_node10"><a xlink:href="https://github.com/NonceGeek/tai_shang_micro_faas_system#distributed-rules" xlink:title="Distributed Rules" target="_blank">
            <polygon fill="none" stroke="#000000" points="131.3758,-52 16.6242,-52 16.6242,-16 131.3758,-16 131.3758,-52"/>
            <text text-anchor="middle" x="74" y="-29.8" font-family="Times,serif" font-size="14.00" fill="#000000">Distributed Rules</text>
            </a>
            </g>
            </g>
            <!-- cluster_3_movedid -->
            <g id="node12" class="node">
            <title>cluster_3_movedid</title>
            <g id="a_node12"><a xlink:href="https://explorer.aptoslabs.com/account/0x1e87fd50b0e297f5c8c05ee0e8516c7cdce991c91c9ce6817c65fcf7bd982602" xlink:title="DID: 0x1e...02" target="_blank">
            <polygon fill="none" stroke="#000000" points="1024.979,-52 925.021,-52 925.021,-16 1024.979,-16 1024.979,-52"/>
            <text text-anchor="middle" x="975" y="-29.8" font-family="Times,serif" font-size="14.00" fill="#000000">DID: 0x1e...02</text>
            </a>
            </g>
            </g>
            <!-- cluster_3_contributors -->
            <g id="node13" class="node">
            <title>cluster_3_contributors</title>
            <g id="a_node13"><a xlink:href="https://github.com/NonceGeek/web3_aptos_ex#contributors" xlink:title="Contributors" target="_blank">
            <polygon fill="none" stroke="#000000" points="907.2745,-52 820.7255,-52 820.7255,-16 907.2745,-16 907.2745,-52"/>
            <text text-anchor="middle" x="864" y="-29.8" font-family="Times,serif" font-size="14.00" fill="#000000">Contributors</text>
            </a>
            </g>
            </g>
            <!-- cluster_3_money_history -->
            <g id="node14" class="node">
            <title>cluster_3_money_history</title>
            <g id="a_node14"><a xlink:href="https://github.com/NonceGeek/web3_aptos_ex#money-history" xlink:title="Money History" target="_blank">
            <polygon fill="none" stroke="#000000" points="802.6523,-52 701.3477,-52 701.3477,-16 802.6523,-16 802.6523,-52"/>
            <text text-anchor="middle" x="752" y="-29.8" font-family="Times,serif" font-size="14.00" fill="#000000">Money History</text>
            </a>
            </g>
            </g>
            <!-- cluster_3_distributed_rules -->
            <g id="node15" class="node">
            <title>cluster_3_distributed_rules</title>
            <g id="a_node15"><a xlink:href="https://github.com/NonceGeek/web3_aptos_ex#distributed-rules" xlink:title="Distributed Rules" target="_blank">
            <polygon fill="none" stroke="#000000" points="683.3758,-52 568.6242,-52 568.6242,-16 683.3758,-16 683.3758,-52"/>
            <text text-anchor="middle" x="626" y="-29.8" font-family="Times,serif" font-size="14.00" fill="#000000">Distributed Rules</text>
            </a>
            </g>
            </g>
            <!-- cluster_4_repo -->
            <g id="node16" class="node">
            <title>cluster_4_repo</title>
            <g id="a_node16"><a xlink:href="https://github.com/NonceGeek/Move-Airdropper-Based-On-Github" xlink:title="Repo" target="_blank">
            <polygon fill="none" stroke="#000000" points="545,-275.2 491,-275.2 491,-239.2 545,-239.2 545,-275.2"/>
            <text text-anchor="middle" x="518" y="-253" font-family="Times,serif" font-size="14.00" fill="#000000">Repo</text>
            </a>
            </g>
            </g>
            <!-- cluster_4_repo&#45;&gt;cluster_1_repo -->
            <g id="edge1" class="edge">
            <title>cluster_4_repo-&gt;cluster_1_repo</title>
            <path fill="none" stroke="#000000" d="M518,-238.7715C518,-221.139 518,-194.2924 518,-173.9391"/>
            <polygon fill="#000000" stroke="#000000" points="521.5001,-173.6855 518,-163.6856 514.5001,-173.6856 521.5001,-173.6855"/>
            <text text-anchor="middle" x="530.8303" y="-208.6" font-family="Times,serif" font-size="14.00" fill="#000000">10%</text>
            </g>
            <!-- cluster_4_contributors -->
            <g id="node17" class="node">
            <title>cluster_4_contributors</title>
            <g id="a_node17"><a xlink:href="https://github.com/NonceGeek/Move-Airdropper-Based-On-Github#contributors" xlink:title="Contributors" target="_blank">
            <polygon fill="none" stroke="#000000" points="473.2745,-275.2 386.7255,-275.2 386.7255,-239.2 473.2745,-239.2 473.2745,-275.2"/>
            <text text-anchor="middle" x="430" y="-253" font-family="Times,serif" font-size="14.00" fill="#000000">Contributors</text>
            </a>
            </g>
            </g>
            <!-- cluster_4_money_history -->
            <g id="node18" class="node">
            <title>cluster_4_money_history</title>
            <g id="a_node18"><a xlink:href="https://github.com/NonceGeek/Move-Airdropper-Based-On-Github#money-history" xlink:title="Money History" target="_blank">
            <polygon fill="none" stroke="#000000" points="368.6523,-275.2 267.3477,-275.2 267.3477,-239.2 368.6523,-239.2 368.6523,-275.2"/>
            <text text-anchor="middle" x="318" y="-253" font-family="Times,serif" font-size="14.00" fill="#000000">Money History</text>
            </a>
            </g>
            </g>
            <!-- cluster_4_distributed_rules -->
            <g id="node19" class="node">
            <title>cluster_4_distributed_rules</title>
            <g id="a_node19"><a xlink:href="https://github.com/NonceGeek/Move-Airdropper-Based-On-Github#distributed-rules" xlink:title="Distributed Rules" target="_blank">
            <polygon fill="none" stroke="#000000" points="249.3758,-275.2 134.6242,-275.2 134.6242,-239.2 249.3758,-239.2 249.3758,-275.2"/>
            <text text-anchor="middle" x="192" y="-253" font-family="Times,serif" font-size="14.00" fill="#000000">Distributed Rules</text>
            </a>
            </g>
            </g>
            <!-- cluster_4_movedid -->
            <g id="node20" class="node">
            <title>cluster_4_movedid</title>
            <g id="a_node20"><a xlink:href="https://explorer.aptoslabs.com/account/0x82b219e76ca10cbcc6a66a547c43a8c72531fb4785548db153f02f552dbf7a55?network=mainnet" xlink:title="DID: 0x82...55" target="_blank">
            <polygon fill="none" stroke="#000000" points="116.2647,-275.2 15.7353,-275.2 15.7353,-239.2 116.2647,-239.2 116.2647,-275.2"/>
            <text text-anchor="middle" x="66" y="-253" font-family="Times,serif" font-size="14.00" fill="#000000">DID: 0x82...55</text>
            </a>
            </g>
            </g>
            </g>
        </svg>
      </.container>
        
      """
    end
end